

function wMockData () {
	const location = {
		user: {
			name: 'James',
			department: {
				dept: 'engineering',
				numberOfPartsDelivered: 52,
				numberOfPendingParts: 9,
			},
			phone: '12345678902',
			whatsapp: '98765432103',
			profile_photo: 'placeholder.png',
			email: 'james@example.com',
			address: '12, kudirat way, lagos',
			status: 'active',
		},
	}
	const parts = [
		'Select Part',
		'GRG Note Transport',
		'GRG Note Presenter',
		'GRG Note Feeder',
		'GRG EPP',
		'GRG Card Reader',
		'GRG PC Board',
		'GRG Shutter',
		'GRG Receipt Printer',
		'GRG Journal Printer',
		'GRG Monitor',
		'GRG PC Core',
		'GRG Display Unit (Rear)',
		'GRG Cassest',
		'GRG Power Supply Unit',
		'GRG SLLS/SLRS Component',

		'Wincor Stacker',
		'Wincor V-Module (DDU)',
		'Wincor Cash Media Dispenser (CMD) Board',
		'Wincor Interface Card/Board',
		'Wincor EPP',
		'Wincor Card Reader',
		'Wincor Clamp',
		'Wincor PC Board',
		'Wincor Shutter',
		'Wincor Receipt Printer',
		'Wincor Journal Printer',
		'Wincor Monitor',
		'Wincor PC Core',
		'Wincor SOP',
		'Wincor Cassest',
		'Wincor Power Supply Unit',

		'NCR Note Presenter',
		'NCR Pick Module',
		'NCR S1 Board',
		'NCR PC Core (Pocono)',
		'NCR PC Core (Teladega)',
		'NCR EPP',
		'NCR Electronic Board',
		'NCR Card Reader',
		'NCR Shutter',
		'NCR Receipt Printer',
		'NCR Journal Printer',
		'NCR Monitor',
		'NCR GOP',
		'NCR Cassest',
		'NCR Power Supply Unit',
		'NCR MEI component',
	]
	const components = [
		'Select component',
		'GRG Sensors (black & white)',
		'GRG MTS',
		'GRG 297 Belts (2 pieces)',
		'GRG 222 Belts (2 pieces)',
		'GRG 235 Belts (2 pieces)',
		'GRG 282 Belts (2 pieces)',
		'GRG 367 Belts (2 pieces)',
		'GRG 218 Belts (2 pieces)',
		'GRG 214 Belts (2 pieces)',
		'GRG 291 Belts (2 pieces)',
		'GRG 292 Belts (2 pieces)',
		'GRG 400 Belts (2 pieces)',

		'Wincor Sensor',
		'Wincor Measuring Station (MS)',
		'Wincor V-Module Transport belts (2)',
		'Wincor V-Module Money Guide',
		'Wincor V-Module Clutch (2)',
		'Wincor V-Module Prisms (2)',
		'Wincor V-Module belts (2)',
		'Wincor V-Module Puller SP (6)',
		'Wincor V-Module Roller Shaft',
		'Wincor V-Module Selenoids (2)',
		'Wincor Clamp Cable',
		'Wincor Clamp Clips (2)',
		'Wincor Clamp Motor',
		'Wincor Clamp Belts (4)',
		'Wincor Clamp Rollers (4)',
		'Wincor Stacker Shafts (2)',
		'Wincor Stacker Belts (4)',
		'Wincor FDK key R/L',
		'Wincor EPROM Flex',
		'Wincor Single Reject Compartment',

		'NCR Track 2 Read Head',
		'NCR Track 3 Read Head',
		'NCR Camera',
		'NCR Air Filter',
		'NCR Capacitor',
		'NCR Pick-Arm',
		'NCR Suction Cups (8 pieces)',
		'NCR Snap Bearings (7 pieces)',
		'NCR LVDT Belts-19 (5 pieces)',
		'NCR LVDT Belts-20 (a piece)',
		'NCR LVDT Belts-21 (4 pieces)',
		'NCR Vertical Belts (2 pieces)',
		'NCR Presenter Belts-625 (3 pieces)',
		'NCR T-Connector',
		'NCR D-Wheel',

		'Random-Access Memory (RAM)',
		'Hard-Disk Drive (HDD)',
		'Chip-Contact',
		'Card Reader Rollers',
		'CMOS Battery',
	]
	return { location, parts, components }
}
export default wMockData;