

function InventoryMockData () {
	const parts = [
		['GRG Note Transport', 6, ],
		['GRG Note Presenter', 3, ],
		['GRG Note Feeder', 12, ],
		['GRG EPP', 2, ],
		['GRG Card Reader', 4, ],
		['GRG PC Board', 15, ],
		['GRG Shutter', 7, ],
		['GRG Receipt Printer', 4, ],
		['GRG Journal Printer', 3, ],
		['GRG Monitor', 3, ],
		['GRG PC Core', 24, ],
		['GRG Display Unit (Rear)', 5, ],
		['GRG Cassest', 13, ],
		['GRG Power Supply Unit', 9, ],
		['GRG SLLS/SLRS Component', 5, ],

		['Wincor Stacker', 3, ],
		['Wincor V-Module (DDU)', 6, ],
		['Wincor Cash Media Dispenser (CMD) Board', 19, ],
		['Wincor Interface Card/Board', 17, ],
		['Wincor EPP', 0, ],
		['Wincor Card Reader', 4, ],
		['Wincor Clamp', 4, ],
		['Wincor PC Board', 1, ],
		['Wincor Shutter', 0, ],
		['Wincor Receipt Printer', 1, ],
		['Wincor Journal Printer', 1, ],
		['Wincor Monitor', 3, ],
		['Wincor PC Core', 3, ],
		['Wincor SOP', 6, ],
		['Wincor Cassest', 0, ],
		['Wincor Power Supply Unit', 2, ],

		['NCR Note Presenter', 6, ],
		['NCR Pick Module', 9, ],
		['NCR S1 Board', 5, ],
		['NCR PC Core (Pocono)', 2, ],
		['NCR PC Core (Teladega)', 1, ],
		['NCR EPP', 7, ],
		['NCR Electronic Board', 1, ],
		['NCR Card Reader', 4, ],
		['NCR Shutter', 5, ],
		['NCR Receipt Printer', 0, ],
		['NCR Journal Printer', 0, ],
		['NCR Monitor', 1, ],
		['NCR GOP', 3, ],
		['NCR Cassest', 2, ],
		['NCR Power Supply Unit', 7, ],
		['NCR MEI component', 4, ],
	]
	const components = [
		['GRG Sensors (black & white)', 200, ],
		['GRG MTS', 15, ],
		['GRG 297 Belts', 500, ],
		['GRG 222 Belts', 246, ],
		['GRG 235 Belts', 344, ],
		['GRG 282 Belts', 390, ],
		['GRG 367 Belts', 368, ],
		['GRG 218 Belts', 450, ],
		['GRG 214 Belts', 198, ],
		['GRG 291 Belts', 30, ],
		['GRG 292 Belts', 96, ],
		['GRG 400 Belts', 124, ],

		['Wincor Sensor', 40, ],
		['Wincor Measuring Station (MS)', 30, ],
		['Wincor V-Module Transport belts', 46, ],
		['Wincor V-Module Money Guide', 20, ],
		['Wincor V-Module Clutch', 16, ],
		['Wincor V-Module Prisms', 18, ],
		['Wincor V-Module belts', 60, ],
		['Wincor V-Module Puller SP', 300, ],
		['Wincor V-Module Roller Shaft', 12, ],
		['Wincor V-Module Selenoids', 16, ],
		['Wincor Clamp Cable', 24, ],
		['Wincor Clamp Clips', 80, ],
		['Wincor Clamp Motor', 10, ],
		['Wincor Clamp Belts', 50, ],
		['Wincor Clamp Rollers', 12, ],
		['Wincor Stacker Shafts', 8, ],
		['Wincor Stacker Belts', 70, ],
		['Wincor FDK key R/L', 14, ],
		['Wincor EPROM Flex', 0, ],
		['Wincor Single Reject Compartment', 20, ],

		['NCR Track 2 Read Head', 24, ],
		['NCR Track 3 Read Head', 12, ],
		['NCR Camera', 16, ],
		['NCR Air Filter', 34, ],
		['NCR Capacitor', 18, ],
		['NCR Pick-Arm', 48, ],
		['NCR Suction Cups', 500, ],
		['NCR Snap Bearings', 480, ],
		['NCR LVDT Belts-19', 120, ],
		['NCR LVDT Belts-20 (a piece)', 100, ],
		['NCR LVDT Belts-21', 110, ],
		['NCR Vertical Belts', 38, ],
		['NCR Presenter Belts-625', 42, ],
		['NCR T-Connector', 24, ],
		['NCR D-Wheel', 6, ],

		['Random-Access Memory (RAM)', 6, ],
		['Hard-Disk Drive (HDD)', 4, ],
		['Chip-Contact', 12, ],
		['Card Reader Rollers', 26, ],
		['CMOS Battery', 16, ],
	]
	return { parts, components }
}
export default InventoryMockData;